### PR TITLE
Do not emit interopDefault helper in commonjs builds

### PR DESCRIPTION
**Pull request by blikblum**
This generates cleaner, smaller code.

Makes easier to use webpack / brfs on node: https://github.com/foliojs/pdfkit/issues/990

### CODE REVIEW

**Comment by devongovett** [comment]
Does this change the way you import the module?

**Comment by blikblum** [comment]
No. Just emits `var fs = require('fs')` instead of `var fs = _interopDefault(require('fs'))`.

**Review by devongovett — APPROVED** [review]

**Comment by kelly-tock** [comment]
I'm seeing an issue in webpack build when I updated this to the latest. 

`TypeError: PDFDocument is not a constructor`

and when I revert to 1.2.2 it is working. 

could this have caused that?

**Comment by kelly-tock** [comment]
nvrmind, I'm getting a range error. disregard. 

`Invalid typed array length: 4034658560`. 

at new Uint8Array (<anonymous>)
    at new UnicodeTrie (webpack-internal:///./node_modules/unicode-trie/index.js:57)
    at eval (webpack-internal:///./node_modules/unicode-properties/unicode-properties.browser.es.js:154)
    at Module../node_modules/unicode-properties/unicode-properties.browser.es.js (8.index.js:1806)
    at __webpack_require__ (index.js:770)
    at fn (index.js:130)
    at Object.eval (webpack-internal:///./node_modules/fontkit/index.js:24)
    at eval (webpack-internal:///./node_modules/fontkit/index.js:14940)
    at Object../node_modules/fontkit/index.js (8.index.js:1389)
    at __webpack_require__ (index.js:770)

any ideas?

**Comment by blikblum** [comment]
See https://github.com/foliojs/unicode-trie/issues/9

**Comment by kelly-tock** [comment]
Yep that was what was installed when I updated to latest of this. Still get the issue above.

**Pull request merged**
